#h2-database config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb
    username: sa
    password: 
  jpa:
    properties:
      hibernate :
        show_sql : true
        
    hibernate:
      ddl-auto: update
  batch:    job:      enabled: true
    initialize-schema: always
      
#logging Config
logging:
  file:    name: d://logs/MobileFoodProject.log
    max-size: 1MB  level:    root: INFO
    org.springframework: ERROR
  pattern:    file: "%p %d{dd-mm-yy}%L %c[%m]-%d %n"
    
server:
  port: 8082
  servlet:
    context-path: /zelish
    
    